version: "3.4"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: flux-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong_Password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  webapi:
    image: cleanarchitecture-webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

volumes:
  sqlserver-data:
